#! /bin/sh

config="$1"

export DATABASE_URL=$(heroku config:get DATABASE_URL);

case $config in
    dev)
        export APP_SETTINGS=backend.config.DevelopmentConfig
        ;;
    test)
        export APP_SETTINGS=backend.config.TestingConfig
        ;;
    prod)
        export APP_SETTINGS=backend.config.ProductionConfig
        ;;
    unconfig)
        unset APP_SETTINGS
        ;;
esac
